{% set name = "dis3" %}
{% set version = "0.1.2" %}
{% set sha256 = "b98e5a9e3d8df54396219c0093fed1454416cec2b74ec15dc63e6a72b3bab94a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1002
  skip: True  # [py3k]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - dis3

about:
  home: https://pypi.python.org/pypi/dis3
  # The home page specified at PyPi (https://github.com/tomxtobin/python-dis3) no longer exists,
  # however it appears that a new repository with the full git history is accessible at,
  # https://github.com/xoviat/python-dis3
  license: MIT
  license_family: MIT
  # the LICENCE file is mentioned in the README but not included in the .tar.gz
  # distributed on PyPi.
  summary: 'Python 2.7 backport of the "dis" module from Python 3.5+'

extra:
  recipe-maintainers:
    - rth
