appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: m4RVf9oykBfJlrdQteMy/Mf/dfr3R+8083iVg9OxpIJk5ToKjq++S/2DWBzkWJZlj1d09Sd0lTUhRG3U06O41wNZg7nlCKjTN9ZVKzcqhJI8BzMsqR7uxxX/dTaYj7awNtTYdXpXJwBgDezTiVOI8orV+cBmDdhSCgk22kFTee6qw49H0sMHXLhuHAfmhJIwfiq42oUqr99F2Qt/jQGiU0cD/rmThp8vOU/2imfTwc8Zjm4Ck5uoWkPipszs3zmVySJo48QnYBPqZzIsgyy+U2ByjrOTlbaMYpxGt8zomWnj887b7Tgws7V4sVhQvWeGMPcmiWU0btQJkpeGZbqKZDVJtDgPQQAd/jQNUf1nMwCu129Q1zvMeszaMBfJFpLR7HO/1KOpkzGcBxwwvO7whoS5mIunitLlxiGVJ1plcpKOJ0W7Zf7FPO6IpErLcIfciYKhRSPeLnY88y7rRBRwFr5fTgY9cZRG9dty4F5lb3MaTkUmsjA/I67I3iED3b5zOwXF1dCcHxygd9cruN7kvU7yPtiWylb9pMJ/AjhkKHgyJXgfNQSnA/ldazS8BwwK3rc5IOZvl6Bqm5HTx8lg5E1USvV8HvGZ9phekeBLW5xpXPPCwswzoxc+2BREDAk5J3O01zElMiZoJACyGAqNG7jKorjzUrtlDGonOdMBj78=}
conda_forge_output_validation: true
